/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as DiscoveryServersRouteImport } from './routes/discovery.servers'
import { Route as AppExploreRouteImport } from './routes/_app.explore'
import { Route as AppChannelsAtmeRouteImport } from './routes/_app.channels.@me'
import { Route as AppChannelsAtmeChannelIdRouteImport } from './routes/_app.channels.@me.$channelId'
import { Route as AppChannelsServerIdChannelIdRouteImport } from './routes/_app.channels.$serverId.$channelId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryServersRoute = DiscoveryServersRouteImport.update({
  id: '/discovery/servers',
  path: '/discovery/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsAtmeRoute = AppChannelsAtmeRouteImport.update({
  id: '/channels/@me',
  path: '/channels/@me',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsAtmeChannelIdRoute =
  AppChannelsAtmeChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AppChannelsAtmeRoute,
  } as any)
const AppChannelsServerIdChannelIdRoute =
  AppChannelsServerIdChannelIdRouteImport.update({
    id: '/channels/$serverId/$channelId',
    path: '/channels/$serverId/$channelId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof AppExploreRoute
  '/discovery/servers': typeof DiscoveryServersRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/channels/@me': typeof AppChannelsAtmeRouteWithChildren
  '/channels/$serverId/$channelId': typeof AppChannelsServerIdChannelIdRoute
  '/channels/@me/$channelId': typeof AppChannelsAtmeChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof AppExploreRoute
  '/discovery/servers': typeof DiscoveryServersRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/channels/@me': typeof AppChannelsAtmeRouteWithChildren
  '/channels/$serverId/$channelId': typeof AppChannelsServerIdChannelIdRoute
  '/channels/@me/$channelId': typeof AppChannelsAtmeChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/explore': typeof AppExploreRoute
  '/discovery/servers': typeof DiscoveryServersRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/_app/channels/@me': typeof AppChannelsAtmeRouteWithChildren
  '/_app/channels/$serverId/$channelId': typeof AppChannelsServerIdChannelIdRoute
  '/_app/channels/@me/$channelId': typeof AppChannelsAtmeChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/discovery/servers'
    | '/users/$userId'
    | '/channels/@me'
    | '/channels/$serverId/$channelId'
    | '/channels/@me/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/discovery/servers'
    | '/users/$userId'
    | '/channels/@me'
    | '/channels/$serverId/$channelId'
    | '/channels/@me/$channelId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/explore'
    | '/discovery/servers'
    | '/users/$userId'
    | '/_app/channels/@me'
    | '/_app/channels/$serverId/$channelId'
    | '/_app/channels/@me/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DiscoveryServersRoute: typeof DiscoveryServersRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/servers': {
      id: '/discovery/servers'
      path: '/discovery/servers'
      fullPath: '/discovery/servers'
      preLoaderRoute: typeof DiscoveryServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/@me': {
      id: '/_app/channels/@me'
      path: '/channels/@me'
      fullPath: '/channels/@me'
      preLoaderRoute: typeof AppChannelsAtmeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/@me/$channelId': {
      id: '/_app/channels/@me/$channelId'
      path: '/$channelId'
      fullPath: '/channels/@me/$channelId'
      preLoaderRoute: typeof AppChannelsAtmeChannelIdRouteImport
      parentRoute: typeof AppChannelsAtmeRoute
    }
    '/_app/channels/$serverId/$channelId': {
      id: '/_app/channels/$serverId/$channelId'
      path: '/channels/$serverId/$channelId'
      fullPath: '/channels/$serverId/$channelId'
      preLoaderRoute: typeof AppChannelsServerIdChannelIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppChannelsAtmeRouteChildren {
  AppChannelsAtmeChannelIdRoute: typeof AppChannelsAtmeChannelIdRoute
}

const AppChannelsAtmeRouteChildren: AppChannelsAtmeRouteChildren = {
  AppChannelsAtmeChannelIdRoute: AppChannelsAtmeChannelIdRoute,
}

const AppChannelsAtmeRouteWithChildren = AppChannelsAtmeRoute._addFileChildren(
  AppChannelsAtmeRouteChildren,
)

interface AppRouteChildren {
  AppExploreRoute: typeof AppExploreRoute
  AppChannelsAtmeRoute: typeof AppChannelsAtmeRouteWithChildren
  AppChannelsServerIdChannelIdRoute: typeof AppChannelsServerIdChannelIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExploreRoute: AppExploreRoute,
  AppChannelsAtmeRoute: AppChannelsAtmeRouteWithChildren,
  AppChannelsServerIdChannelIdRoute: AppChannelsServerIdChannelIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DiscoveryServersRoute: DiscoveryServersRoute,
  UsersUserIdRoute: UsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
