use utoipa::OpenApi;

use super::handlers::{
    crypto::{
        backup::__path_get_key_backup_handler,
        backup::__path_upsert_key_backup_handler,
        bundle::__path_get_key_bundle_handler,
        devices::__path_delete_device_handler,
        devices::__path_list_devices_handler,
        devices::__path_register_device_handler,
        dm_session::__path_create_dm_session_handler,
        dm_session::__path_get_dm_session_handler,
        dm_session::__path_update_dm_session_handler,
        identity::__path_get_identity_key_handler,
        identity::__path_upload_identity_key_handler,
        prekeys::__path_upload_onetime_prekeys_handler,
        prekeys::__path_upload_signed_prekey_handler,
        sender_keys::__path_distribute_sender_keys_handler,
        sender_keys::__path_get_sender_keys_handler,
    },
    dm::{
        create_or_get::__path_create_or_get_dm_handler,
        delete_message::__path_delete_dm_message_handler,
        get_messages::__path_get_dm_messages_handler, list_dms::__path_list_dms_handler,
        history_sync::{
            __path_complete_dm_history_sync_job_handler,
            __path_create_dm_history_sync_job_handler,
            __path_fail_dm_history_sync_job_handler,
            __path_get_dm_history_sync_job_handler,
            __path_list_dm_history_sync_messages_handler,
            __path_upload_dm_history_sync_payloads_handler,
        },
        send_message::__path_send_dm_message_handler,
    },
    guild::{
        assign_member_role::__path_assign_member_role_handler,
        channel::{
            create_channel::__path_create_channel_handler,
            delete_channel::__path_delete_channel_handler,
            delete_message::__path_delete_message_handler,
            get_channels::__path_get_channels_handler, get_messages::__path_get_messages_handler,
            send_message::__path_send_message_handler,
            update_channel::__path_update_channel_handler,
        },
        create_guild::__path_create_guild_handler,
        create_role::__path_create_role_handler,
        delete_guild::__path_delete_guild_handler,
        delete_role::__path_delete_role_handler,
        get_members::__path_get_members_handler,
        get_role::__path_get_role_handler,
        get_roles::__path_get_roles_handler,
        invite::{
            create_invite::__path_create_invite_handler,
            delete_invite::__path_delete_invite_handler, join_guild::__path_join_guild_handler,
            list_invites::__path_list_invites_handler,
            preview_invite::__path_preview_invite_handler,
        },
        leave_guild::__path_leave_guild_handler,
        remove_member_role::__path_remove_member_role_handler,
        update_guild::__path_update_guild_handler,
        update_role::__path_update_role_handler,
    },
    user::{
        friends::{
            accept::__path_accept_friend_request_handler,
            decline::__path_decline_friend_request_handler,
            list_friends::__path_list_friends_handler, list_incoming::__path_list_incoming_handler,
            list_outgoing::__path_list_outgoing_handler, remove::__path_remove_friend_handler,
            send_request::__path_send_friend_request_handler,
        },
        get_me::__path_get_me_handler,
        get_user::__path_get_user_handler,
        get_user_guilds::__path_get_user_guilds,
        update_profile::__path_update_profile_handler,
    },
};

#[derive(OpenApi)]
#[openapi(
    info(title = "FerrisCord API"),
    paths(
        create_guild_handler,
        delete_guild_handler,
        create_role_handler,
        delete_role_handler,
        get_role_handler,
        get_roles_handler,
        update_role_handler,
        get_channels_handler,
        create_channel_handler,
        delete_channel_handler,
        get_messages_handler,
        send_message_handler,
        create_invite_handler,
        list_invites_handler,
        delete_invite_handler,
        join_guild_handler,
        preview_invite_handler,
        get_user_guilds,
        get_me_handler,
        get_user_handler,
        update_profile_handler,
        update_channel_handler,
        assign_member_role_handler,
        remove_member_role_handler,
        update_guild_handler,
        get_members_handler,
        delete_message_handler,
        leave_guild_handler,
        // DM handlers
        list_dms_handler,
        create_or_get_dm_handler,
        get_dm_messages_handler,
        send_dm_message_handler,
        delete_dm_message_handler,
        create_dm_history_sync_job_handler,
        get_dm_history_sync_job_handler,
        list_dm_history_sync_messages_handler,
        upload_dm_history_sync_payloads_handler,
        complete_dm_history_sync_job_handler,
        fail_dm_history_sync_job_handler,
        // Friends handlers
        list_friends_handler,
        list_incoming_handler,
        list_outgoing_handler,
        send_friend_request_handler,
        accept_friend_request_handler,
        decline_friend_request_handler,
        remove_friend_handler,
        // Crypto / E2EE handlers
        upload_identity_key_handler,
        get_identity_key_handler,
        register_device_handler,
        list_devices_handler,
        delete_device_handler,
        upload_signed_prekey_handler,
        upload_onetime_prekeys_handler,
        get_key_bundle_handler,
        upsert_key_backup_handler,
        get_key_backup_handler,
        distribute_sender_keys_handler,
        get_sender_keys_handler,
        create_dm_session_handler,
        get_dm_session_handler,
        update_dm_session_handler,
    )
)]
pub struct ApiDoc;
